-- =============================================================================
-- TestContainers Oracle 初始化腳本
-- 使用 withInitScript() 在連線用戶 (CV) 的 schema 中建立表格
-- CV 用戶連線後，CV.CRAT 等同於 CRAT（當前 schema）
-- =============================================================================

-- 1. 佣金率表 (CRAT)
CREATE TABLE CRAT (
    CRAT_SERIAL       NUMBER(10)     NOT NULL,
    COMM_CLASS_CODE   VARCHAR2(10)   NOT NULL,
    COMM_LINE_CODE    VARCHAR2(10)   NOT NULL,
    CRAT_TYPE         VARCHAR2(2),
    PROJ_NO           VARCHAR2(10),
    STR_DATE          DATE           NOT NULL,
    END_DATE          DATE           NOT NULL,
    CRAT_KEY1         VARCHAR2(10),
    CRAT_KEY2         VARCHAR2(10),
    COMM_START_YEAR   NUMBER(5),
    COMM_END_YEAR     NUMBER(5),
    COMM_START_AGE    NUMBER(5),
    COMM_END_AGE      NUMBER(5),
    COMM_START_MODX   NUMBER(5),
    COMM_END_MODX     NUMBER(5),
    COMM_RATE         NUMBER(10,6)   NOT NULL,
    COMM_RATE_ORG     NUMBER(10,6),
    PREM_LIMIT_STR    NUMBER(15,2),
    PREM_LIMIT_END    NUMBER(15,2),
    CONSTRAINT PK_CRAT PRIMARY KEY (CRAT_SERIAL)
);

CREATE INDEX IDX_CRAT_CLASS_CODE ON CRAT(COMM_CLASS_CODE);

CREATE INDEX IDX_CRAT_LINE_CODE ON CRAT(COMM_LINE_CODE);

-- CRAT 序列 (用於 CUD 操作)
CREATE SEQUENCE CRAT_SEQ START WITH 1 INCREMENT BY 1;

-- 2. 承保範圍表 (CVCO)
CREATE TABLE CVCO (
    POLICY_NO         VARCHAR2(10)   NOT NULL,
    COVERAGE_NO       NUMBER(5)      NOT NULL,
    PLAN_CODE         VARCHAR2(5)    NOT NULL,
    VERSION           VARCHAR2(3)    NOT NULL,
    RATE_SEX          VARCHAR2(1)    NOT NULL,
    RATE_AGE          NUMBER(5)      NOT NULL,
    RATE_SUB_1        VARCHAR2(10)   NOT NULL,
    RATE_SUB_2        VARCHAR2(10)   NOT NULL,
    CO_ISSUE_DATE     DATE           NOT NULL,
    CO_STATUS_CODE    VARCHAR2(1)    NOT NULL,
    INSURANCE_TYPE_3  VARCHAR2(1)    NOT NULL,
    PROCESS_DATE      DATE           NOT NULL,
    PROCESS_TYPE      VARCHAR2(2)    NOT NULL,
    POLICY_TYPE       VARCHAR2(1),
    CO_STATUS_CODE2   VARCHAR2(1),
    CONSTRAINT PK_CVCO PRIMARY KEY (POLICY_NO, COVERAGE_NO)
);

CREATE INDEX IDX_CVCO_PLAN_CODE ON CVCO(PLAN_CODE);

CREATE INDEX IDX_CVCO_STATUS ON CVCO(CO_STATUS_CODE);

-- 3. 產品單位表 (CVPU)
CREATE TABLE CVPU (
    POLICY_NO          VARCHAR2(10)   NOT NULL,
    COVERAGE_NO        NUMBER(5)      NOT NULL,
    PS06_TYPE          VARCHAR2(1)    NOT NULL,
    CVPU_TYPE          VARCHAR2(1)    NOT NULL,
    LAST_ANNIV_DUR     NUMBER(5)      NOT NULL,
    CVPU_STATUS_CODE   VARCHAR2(1),
    DIV_DECLARE        NUMBER(15,2)   DEFAULT 0,
    DIV_PUA_AMT        NUMBER(15,2)   DEFAULT 0,
    FINANCIAL_DATE     DATE,
    PCPO_NO            VARCHAR2(10),
    PROGRAM_ID         VARCHAR2(10),
    PROCESS_DATE       DATE,
    POLICY_TYPE        VARCHAR2(1),
    CVPU_APPROVED_DATE DATE,
    PROGRAM_ID_CVPU    VARCHAR2(10),
    CONSTRAINT PK_CVPU PRIMARY KEY (POLICY_NO, COVERAGE_NO, PS06_TYPE, CVPU_TYPE, LAST_ANNIV_DUR)
);

CREATE INDEX IDX_CVPU_COVERAGE ON CVPU(POLICY_NO, COVERAGE_NO);

-- 4. 紅利分配水準表 (CVDI)
CREATE TABLE CVDI (
    PLAN_CODE         VARCHAR2(5)    NOT NULL,
    VERSION           VARCHAR2(1)    NOT NULL,
    PAID_STATUS       VARCHAR2(2)    NOT NULL,
    RATE_SEX          VARCHAR2(1)    NOT NULL,
    AGE_LIMIT_STR     NUMBER(5)      NOT NULL,
    AGE_LIMIT_END     NUMBER(5)      NOT NULL,
    FACE_AMT_STR      NUMBER(10)     NOT NULL,
    FACE_AMT_END      NUMBER(10)     NOT NULL,
    MODE_PREM_S       NUMBER(12,2)   NOT NULL,
    MODE_PREM_E       NUMBER(12,2)   NOT NULL,
    POLICY_YEAR       NUMBER(5)      NOT NULL,
    DECL_DATE         DATE           NOT NULL,
    RATE_RATIO        NUMBER(7,6),
    DEATH_RATIO       NUMBER(7,6),
    LOADING_RATIO     NUMBER(7,6),
    REWARD_RATIO      NUMBER(7,6),
    DEATH_1_RATIO     NUMBER(7,6),
    DEATH_2_RATIO     NUMBER(7,6),
    RATIO_FEE         NUMBER(8,6),
    FIX_FEE           NUMBER(10,4),
    DET_BIR_RATE      NUMBER(7,6),
    CONFIRM_FLAG      VARCHAR2(1),
    CONFIRM_OPER      VARCHAR2(8),
    CONFIRM_DATE      DATE,
    AVERAGE_DISCOUNT  NUMBER(7,6),
    CONSTRAINT PK_CVDI PRIMARY KEY (PLAN_CODE, VERSION, PAID_STATUS, RATE_SEX,
        AGE_LIMIT_STR, AGE_LIMIT_END, FACE_AMT_STR, FACE_AMT_END,
        MODE_PREM_S, MODE_PREM_E, POLICY_YEAR, DECL_DATE)
);

CREATE INDEX IDX_CVDI_PLAN ON CVDI(PLAN_CODE, VERSION);

-- 5. 準備金因子表 (CVRF)
CREATE TABLE CVRF (
    PLAN_CODE         VARCHAR2(5)    NOT NULL,
    VERSION           VARCHAR2(1)    NOT NULL,
    DUR_TYPE          NUMBER(5)      NOT NULL,
    DUR_YEAR          NUMBER(5),
    COLL_YEAR         NUMBER(5),
    PAY_MODE          NUMBER(5),
    INSURED_TYPE      NUMBER(5),
    PO_RVF_DEATH      NUMBER(5),
    PO_RVF_RATE       NUMBER(5,2),
    RVF_DEATH         NUMBER(5),
    RVF_RATE          NUMBER(5,2),
    PO_RVF_TSO        VARCHAR2(5),
    RVF_TSO           VARCHAR2(5),
    ET_RVF_RATE       NUMBER(5,2),
    ET_RVF_TSO_IND    VARCHAR2(3),
    RBN_TYPE          VARCHAR2(1),
    SBN_TYPE          VARCHAR2(1),
    I2_6_OR_NOT       VARCHAR2(1),
    I2_6_PRAT         NUMBER(5,2),
    ACCI_OR_NOT       VARCHAR2(1),
    ACCI_PRAT         NUMBER(5,2),
    RET_PREM_IND      VARCHAR2(1),
    RETURN_INT_TYPE   VARCHAR2(1),
    RETURN_INT        NUMBER(5,2),
    RETURN_COST_F     VARCHAR2(1)    NOT NULL,
    MODIFY_RV_IND     VARCHAR2(1)    NOT NULL,
    RECORD_TYPE_10    VARCHAR2(10)   NOT NULL,
    MIX_RVF_IND       VARCHAR2(3)    NOT NULL,
    RET_PREM_IND2     VARCHAR2(1),
    ET_PO_RVF_RATE    NUMBER(5,2),
    ET_PO_RVF_TSO_IND VARCHAR2(3),
    ET_ACCI_IND       VARCHAR2(1),
    ET_ACCI_RATE      NUMBER(10,9),
    CONSTRAINT PK_CVRF PRIMARY KEY (PLAN_CODE, VERSION, DUR_TYPE)
);

CREATE INDEX IDX_CVRF_PLAN ON CVRF(PLAN_CODE, VERSION);

-- 6. 險種描述表 (PLDF) - 對應 V3.PLDF
-- ADR-022: PLDF 業務歸屬於 CV 模組 (非 PC)
CREATE TABLE PLDF (
    -- 主鍵
    PLAN_CODE           VARCHAR2(5)    NOT NULL,
    VERSION             VARCHAR2(1)    NOT NULL,

    -- 基本資訊
    PLAN_TITLE          VARCHAR2(40),
    PLAN_NAME           VARCHAR2(50),
    CONTRACTED_NAME     VARCHAR2(40),

    -- 年齡限制
    LOW_AGE             NUMBER(5)      NOT NULL,
    HIGH_AGE            NUMBER(5)      NOT NULL,
    LOW_AGE_SUB         NUMBER(5),
    HIGH_AGE_SUB        NUMBER(5),
    LOW_AGE_IND         VARCHAR2(1),
    HIGH_AGE_IND        VARCHAR2(1),
    REN_HIGH_AGE_IND    VARCHAR2(1),
    REN_HIGH_AGE        NUMBER(5),

    -- 繳費/保障年期
    COLLECT_YEAR_IND    VARCHAR2(1)    NOT NULL,
    COLLECT_YEAR        NUMBER(5),
    EXP_YEAR_IND        VARCHAR2(1)    NOT NULL,
    EXP_YEAR            NUMBER(5),

    -- 上市日期
    PLAN_START_DATE     DATE           NOT NULL,
    PLAN_END_DATE       DATE           NOT NULL,

    -- 險種分類
    PRIMARY_RIDER_IND   VARCHAR2(1),
    RIDER_IND           VARCHAR2(1),
    PLAN_RELATION       VARCHAR2(1),
    PLAN_RELATION_SUB   VARCHAR2(1),
    INSURANCE_TYPE      VARCHAR2(1),
    INSURANCE_TYPE_2    VARCHAR2(1),
    INSURANCE_TYPE_3    VARCHAR2(1),
    INSURANCE_TYPE_4    VARCHAR2(1),
    INSURANCE_TYPE_5    VARCHAR2(1),
    PLAN_TYPE           VARCHAR2(1),

    -- 幣別與會計
    CURRENCY_1          VARCHAR2(3)    NOT NULL,
    ACNT_TYPE           VARCHAR2(2),
    PLAN_ACCOUNT_IND    VARCHAR2(1)    NOT NULL,

    -- 紅利設定
    DIV_TYPE            VARCHAR2(2),
    DIV_START_YEAR      NUMBER(5),
    DIV_PAY_ITEM_IND    VARCHAR2(4),
    DIV_CALC_ITEM_IND   VARCHAR2(4),
    CV_DIV_CODE         VARCHAR2(5),
    DIV_SW_M            VARCHAR2(1)    NOT NULL,

    -- 給付/保障
    DEATH_BENEF_IND     VARCHAR2(1),
    SURRENDER_IND       VARCHAR2(1),
    LBENF               VARCHAR2(1),
    MBENF               VARCHAR2(1),
    DBENF               VARCHAR2(1),
    BBENF               VARCHAR2(1),
    BENEF_IND           VARCHAR2(5),

    -- 計算類型
    CSV_CALC_TYPE       VARCHAR2(3)    NOT NULL,
    PUA_CALC_TYPE       VARCHAR2(4)    NOT NULL,
    ETE_CALC_TYPE       VARCHAR2(6)    NOT NULL,

    -- 貸款
    LOAN_AVAL_IND       VARCHAR2(1),
    LOAN_PLAN_CODE      VARCHAR2(5),
    LOAN_VERSION        VARCHAR2(1),
    LOAN_AVAL_PERCENT   NUMBER(5),

    -- 佣金
    COMM_CLASS_CODE     VARCHAR2(5),
    COMM_CLASS_CODE_I   VARCHAR2(1),
    PROD_CLASS_CODE     VARCHAR2(3),

    -- 關聯險種
    UW_PLAN_CODE        VARCHAR2(5)    NOT NULL,
    UW_VERSION          VARCHAR2(1)    NOT NULL,
    CV_PLAN_CODE        VARCHAR2(5),
    CV_VERSION          VARCHAR2(1),
    PC_PLAN_CODE        VARCHAR2(5),
    PC_VERSION          VARCHAR2(1),
    RATE_PLAN_CODE      VARCHAR2(5),
    RATE_VERSION        VARCHAR2(1),
    TREATY_CODE         VARCHAR2(7),

    -- 費率參數
    RATE_SEX_IND        VARCHAR2(1),
    RATE_AGE_IND        VARCHAR2(1),
    RATE_SUB_1_IND      VARCHAR2(1),
    RATE_SUB_2_IND      VARCHAR2(1),

    -- 保費相關
    PREM_CALC_TYPE      VARCHAR2(1),
    PREM_VALUE          NUMBER(5,4),
    PREM_LACK_IND       VARCHAR2(1)    NOT NULL,
    FACE_AMT_UNIT       NUMBER(10),
    TOP_FACE_AMT        NUMBER(10),
    FACE_AMT_TYPE       VARCHAR2(1),

    -- 年金/其他
    ANNY_SW             VARCHAR2(1)    NOT NULL,
    PERSIST_REWARD_IND  VARCHAR2(1)    NOT NULL,
    PERSIST_PREM_VAL    NUMBER(5)      NOT NULL,

    CONSTRAINT PK_PLDF PRIMARY KEY (PLAN_CODE, VERSION)
);

CREATE INDEX IDX_PLDF_INSURANCE_TYPE3 ON PLDF(INSURANCE_TYPE_3);

CREATE INDEX IDX_PLDF_PRIMARY_RIDER ON PLDF(PRIMARY_RIDER_IND);

CREATE INDEX IDX_PLDF_PLAN_TYPE ON PLDF(PLAN_TYPE);

CREATE INDEX IDX_PLDF_DATES ON PLDF(PLAN_START_DATE, PLAN_END_DATE);

-- 7. 費率表 (PRAT) - Plan Rate
CREATE TABLE PRAT (
    PLAN_CODE         VARCHAR2(20)   NOT NULL,
    VERSION           VARCHAR2(4)    NOT NULL,
    RATE_SEX          VARCHAR2(4)    NOT NULL,
    RATE_SUB_1        VARCHAR2(8)    NOT NULL,
    RATE_SUB_2        VARCHAR2(12)   NOT NULL,
    RATE_AGE          NUMBER(5)      NOT NULL,
    ANNUAL_PREM       NUMBER(9,3)    NOT NULL,
    ANNUAL_PREM2      NUMBER(9,3),
    EMPLOYEE_DISC     NUMBER(7,4),
    LOADING_RATE2     NUMBER(5,2),
    CONSTRAINT PK_PRAT PRIMARY KEY (PLAN_CODE, VERSION, RATE_SEX, RATE_SUB_1, RATE_SUB_2, RATE_AGE)
);

CREATE INDEX IDX_PRAT_PLAN_CODE ON PRAT(PLAN_CODE);

CREATE INDEX IDX_PRAT_PLAN_VERSION ON PRAT(PLAN_CODE, VERSION);
